% Script to compare feature

%% Clear the console and environment
clear all
close all

%% Load the scripts from subfolders
% reference https://uk.mathworks.com/matlabcentral/answers/247180-how-may-i-add-all-subfolders-in-my-matlab-path
folder = fileparts(which(mfilename));
addpath(genpath(folder));

%% Images Aquisition
positives = loadimages("../dataset/images/pos/");
negatives = loadimages("../dataset/images/neg/");
positives.labels = ones(positives.number, 1);
negatives.labels = zeros(negatives.number, 1);

%% Feature Extraction on training set
features = featureExtraction(positives, negatives);
rng(3064);

%% Fit the svm model using features generated by HOG
accuracyHOG = crossValidatedAccuracy(features.HOG, 5);

%% Fit the svm model using features generated by Colour Histogram RGB
accuracyColourHistogramRGB = crossValidatedAccuracy(features.ColourHistogramRGB, 5);

%% Fit the svm model using features generated by Colour Histogram HSV
accuracyColourHistogramHSV = crossValidatedAccuracy(features.ColourHistogramHSV, 5);

%% Fit the svm model using features generated by Combined Colour Histogram features
colourHistogramsCombined = join(features.ColourHistogramRGB, features.ColourHistogramHSV, "Keys", "Name", "KeepOneCopy", "Label");
accuracyColourHistogramsCombined = crossValidatedAccuracy(colourHistogramsCombined, 5);

%% Fit the svm model using features generated by Raw Data
accuracyRawData = crossValidatedAccuracy(features.RawData, 5);

%% Compare accuracies
fprintf("Accuracy matrix for HOG:")
accuracyHOG

fprintf("Accuracy matrix for Colour Histogram RGB:")
accuracyColourHistogramRGB

fprintf("Accuracy matrix for Colour Histogram HSV:")
accuracyColourHistogramHSV

fprintf("Accuracy matrix for Combined Colour Histograms:")
accuracyColourHistogramsCombined

fprintf("Accuracy matrix for Raw Data:")
accuracyRawData
