% Script to compare feature

%% Clear the console and environment
clear all
close all

%% Load the scripts from subfolders
% reference https://uk.mathworks.com/matlabcentral/answers/247180-how-may-i-add-all-subfolders-in-my-matlab-path
folder = fileparts(which(mfilename));
addpath(genpath(folder));

%% Images Aquisition
positives = loadimages("../dataset/images/pos/");
negatives = loadimages("../dataset/images/neg/");
positives.labels = ones(positives.number, 1);
negatives.labels = zeros(negatives.number, 1);

%% Feature Extraction on training set
features = featureExtraction(positives, negatives);

%% Fit the svm model using features generated by HOG
accuracyHOG = crossValidatedAccuracy(features.HOG, 5);

%% Fit the svm model using features generated by ColourHistogram
accuracyColourHistogram = crossValidatedAccuracy(features.ColourHistogram, 5);

%% Fit the svm model using features generated by Combined features
accuracyCombined = crossValidatedAccuracy(features.Combined, 5);

%% Compare accuracies
fprintf("Accuracy matrix for HOG:")
accuracyHOG

fprintf("Accuracy matrix for Colour Histogram:")
accuracyColourHistogram

fprintf("Accuracy matrix for Combined:")
accuracyCombined
