% Script to compare feature

%% Clear the console and environment
clear all
close all

%% Load the scripts from subfolders
% reference https://uk.mathworks.com/help/matlab/ref/genpath.html
paths=genpath("./");
addpath(paths);

%% Images Aquisition
positives = loadimages("../dataset/images/pos/");
negatives = loadimages("../dataset/images/neg/");
positives.labels = ones(positives.number, 1);
negatives.labels = zeros(negatives.number, 1);

%% Feature Extraction on training set
features = featureExtraction(positives, negatives);
rng(3064);

%% Fit the svm model using features generated by HOG
accuracyHOG = crossValidatedAccuracy(@svmTrain, features.HOG, 5);

%% Fit the svm model using features generated by Colour Histogram RGB
accuracyColourHistogramRGB = crossValidatedAccuracy(@svmTrain, features.ColourHistogramRGB, 5);

%% Fit the svm model using features generated by Colour Histogram HSV
accuracyColourHistogramHSV = crossValidatedAccuracy(@svmTrain, features.ColourHistogramHSV, 5);

%% Fit the svm model using features generated by Raw Data
accuracyRawData = crossValidatedAccuracy(@svmTrain, features.RawData, 5);

%% Compare accuracies
fprintf("Accuracy matrix for HOG:")
accuracyHOG

fprintf("Accuracy matrix for Colour Histogram RGB:")
accuracyColourHistogramRGB

fprintf("Accuracy matrix for Colour Histogram HSV:")
accuracyColourHistogramHSV

fprintf("Accuracy matrix for Raw Data:")
accuracyRawData
